### ISSUE TITLE
Compilation failing when using "custom gmp" in 4.4 unstable

### ISSUE THREAD

**Issue by PFOllagnon** [manuel-serrano/bigloo#56]
When building 4.4 unstable, custom gmp library is successfully compiled but the directory is not in the -L list:

bigloo-unstable/runtime $ gcc -shared -o libbigloo_u-4.4a.so -Wl,-soname=lib .....
---
bin/ld: cannot find -lgmp
collect2: error: ld returned 1 exit status

It works for this .so when adding -L/OpenSource/bigloo/bigloo-unstable/gmp/OpenSource/INSTALL/bigloo4.4a/lib/bigloo/4.4a/

**Comment by manuel-serrano** [comment]
Thank you for reporting about that problem. It is now fixed in the release 4.4a-2.

**Comment by PFOllagnon** [comment]
Hello Manuel,

The fix you did isn't working here. I still have the issue.
By the way I have now
/bin/ld: cannot find -lunistring
/bin/ld: cannot find -lgmp

What I found is that uncommenting the lines of the configure in the previous version make it works:
   lcustomflags="-L$bootdir/libunistring$libdir/$fildir $lcustomflags"
   lcustomflags="-L$bootdir/pcre$libdir/$fildir $lcustomflags"
   lcustomflags="-L$bootdir/libunistring$libdir/$fildir $lcustomflags"
 
There is also those lines to uncoment or .h files are not found:

 cflags="-I$bootdir/pcre$libdir/$fildir $cflags"
 cflags="-I$bootdir/libunistring$libdir/$fildir $cflags"

Best regards

**Comment by c4augustus** [comment]
This is also a problem on macOS M1, with the current master branch as of 2023.03.24. Neither fixes above solve it, as it appears that the link flags don't include the directory of the local build of libunistring.
